### ISSUE TITLE
プロフィール取得API

### ISSUE THREAD

**Issue by tyokinuhata** [uyupun/mitsu#111]

**Comment by takashi0602** [comment]
```
{
  user_id: xxxx,
  icon: 1,
  rate: 1200,
  history: {
    win: 10,
    lose: 5,
  },
}
```

**Comment by takashi0602** [comment]
DB

 profiles

|  カラム |  タイプ  | 説明 |
| --- | --- | --- |
| id |  int  | プロフィールのID |
| user_id  |  int  | ユーザーのID |
| icon_id | int | ユーザーのアイコン |
| rate | int | レート数 |

histories

|  カラム |  タイプ  | 説明 |
| --- | --- | --- |
| id |  int  | 戦績のID |
| user_id  |  int  | ユーザーのID |
| win | int | 勝利数 |
| lose | int | 敗北数 |
