### ISSUE TITLE
API設計煮詰める会

### ISSUE THREAD

**Issue by tyokinuhata** [uyupun/mitsu#3]
WebSocketオンリーでいけそう？

**Comment by takashi0602** [comment]
[メモ]
ワールドID発行API
-> GET
-> リクエスト: pekoraかbaikinKun
-> レスポンス: 6桁のハッシュ値, トークン発行
-> サーバー側: トークンとpekoraかbaikinKunかをマッピング

ワールド作成側の参加API
-> POST
-> リクエスト: ルームID, トークン
-> レスポンス: なし
-> サーバー側: サーバーpush

ワールド参加側の参加API
-> POST
-> リクエスト: ルームID
-> レスポンス: トークン
-> サーバー側: サーバーpush

**Comment by tyokinuhata** [comment]
WebSocketオンリーではない
