### ISSUE TITLE
WebSocketのエラー処理周り

### ISSUE THREAD

**Issue by tyokinuhata** [uyupun/mitsu#63]
- ルームに３人目来た場合は？
- ~~タブ３つ開いた時に操作できない問題~~
- エラー処理見直し(ブラウザを直接落とした場合とかどうなる？)

**Comment by takashi0602** [comment]
ブラウザの削除、ブラウザの更新は以下で取得可能(コンソールには`reason: transport close`とはかれる)
```
socket.on('disconnect', (reason) => {
  // console.log('reason: ', reason)
});
```

**Comment by takashi0602** [comment]
暗黙的にdisconnectされるかどうか
🙆‍♂️ブラウザの削除
🙆‍♂️ブラウザの更新
🙅‍♂️ブラウザバック
