### ISSUE TITLE
this._dealersで管理するのをやめる

### ISSUE THREAD

**Issue by takashi0602** [uyupun/mitsu#85]
現状のlobby.js内の`this._dealers`で管理しているものを[data store](https://www.npmjs.com/package/data-store)等で管理するように実装し直す
実装後redisも削除するようにする

**Comment by tyokinuhata** [comment]
- https://www.npmjs.com/package/js-data
- https://www.npmjs.com/package/cache-base

ここらへんのとかも

**Comment by tyokinuhata** [comment]
比較

cache-base
- lasy publish: 3 years ago
- weekly downloads: 14,656,684
- documents: https://alloyui.com/api/modules/cache-base.html
- repository: https://github.com/jonschlinkert/cache-base

**Comment by tyokinuhata** [comment]
オレオレで作るという手もあるな
npmで公開する前提で作るとか

**Comment by tyokinuhata** [comment]
https://www.it-swarm-ja.tech/ja/javascript/javascript%E3%82%AA%E3%83%96%E3%82%B8%E3%82%A7%E3%82%AF%E3%83%88%E3%81%AE%E9%85%8D%E5%88%97%E5%86%85%E3%81%AEid%E3%81%A7%E3%82%AA%E3%83%96%E3%82%B8%E3%82%A7%E3%82%AF%E3%83%88%E3%82%92%E6%8E%A2%E3%81%99/939972278/

**Comment by tyokinuhata** [comment]
https://qiita.com/pentla/items/a87383903a30d7baa282

**Comment by tyokinuhata** [comment]
https://qiita.com/toshi-toma/items/ea76b8894e7771d47e10

**Comment by tyokinuhata** [comment]
created_atを追加する

**Comment by tyokinuhata** [comment]
プレイ終了後かどうかのデータも持たせたいな

**Comment by tyokinuhata** [comment]
- [ ] Dealerをシングルトンにする
- [ ] Lobbyを廃止する
- [ ] Worldのstatusを持たせる
- [ ] created_atを持たせる

**Comment by tyokinuhata** [comment]
リファクタ
