### ISSUE TITLE
エラー処理周り 追加修正

### ISSUE THREAD

**Issue by tyokinuhata** [uyupun/mitsu#88]
- [ ] invalid_playerがMitsu側で呼び出された際に、disconnectをしていないのでdisconnectを行うようにする
- [ ] ブラウザのリロード/閉じるなどのオペレーション以外で極力ソシャレ側からdisconnectしないようにする
  - 現状を見るとポーズメニューからゲームを辞めたパターンとnotice_disconnectをlistenしたパターンでソシャレ側からdisconnectしている
  - これを、Mitsu側にdisconnectEmitterを作って対応する
  - ソシャレ側ではdisconnectをlistenするようにし、notice_disconnectは廃止する
- [ ] 勝利パターン（ゲームが収束するパターン）でdisconnectが呼び出されていない気がする。Mitsu側からdisconnectするよう修正する

**Comment by takashi0602** [comment]
以下試してみたが、他人の接続切れなかった
```
🙅‍♂️ this._io.to(this._worldId).disconnect()
🙅‍♂️ this._io.sockets.to(this._worldId).disconnect()
🙅‍♂️ socket.broadcast.to(this._worldId)
```

**Comment by takashi0602** [comment]
- [ ] クライアント側でdisconnectするようにする
- [ ] leave_worldイベントを削除する
